language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - composer install

script:
  - php vendor/bin/phpunit
  - php vendor/bin/phpcs --standard=PSR2 src test

notifications:
  irc: "irc.freenode.org#islandora"

after_success:
  - bash <(curl -s https://codecov.io/bash)
